<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>TarkovCheat.Loader</RootNamespace>
    <AssemblyName>tarkovcheat</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../tarkov-cheat.Core/tarkov-cheat.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
